### PR TITLE
Ruby 3 upgrades

### PR DESCRIPTION
**Pull request by chadmetcalf-cb**
The Jaeger ruby client required a bunch of changes to make ruby 3 compatible besides the small kwargs shim that we initially attempted.

Updated RSpec and Rubocop along with the required Ruby 3 upgrades

### CODE REVIEW

**Comment by indrekj** [comment]
A lot of good stuff here.

Is the `spec.required_ruby_version = '>= 3.0'` line required? I didn't notice any changes that wouldn't work with 2.7. Can you also change https://github.com/salemove/jaeger-client-ruby/blob/master/.travis.yml#L5 to include 3.0

**Comment by chadmetcalf-cb** [comment]
@indrekj  The `spec.required_ruby_version = '>= 3.0'` was a rubocop suggestion. You are absolutely right. All of these changes should work with >= 2.7. I'll update travis accordingly.

**Comment by indrekj** [comment]
Ruby tests seem to be passing, but something with crossdock is failing in travis. I'll take a look tomorrow.

**Comment by chadmetcalf-cb** [comment]
Thanks for your fast help!

I'm not sure if there is a good path to update the base image for the crossdock Dockerfile so that it correctly tests 2.7.2 and 3.0 without dragging in unbeneficial complexity.

I'm going to point it at 3.0 for now.

**Pull request closed without merging**
